### ISSUE TITLE
Question: Are there really infinite keys?

### ISSUE THREAD

**Issue by ghost** [fritzo/rationalkeyboard#2]

**Comment by fritzo** [comment]
Yes and no. The model that the web app is based on indeed has infintely many keys. There is a distance metric on the rational numbers. For practical purposes I limited the web app to 279 numbers (take a look at the javascript console).

One could implement the true infinite keyboard in with maybe 1000 more lines of javascript, by dynamically generating new keys as the user got close to them. However there isn't any interesting structure away from the 1/1 origin: the neighborhood around any p/q looks the same in the distance metric, and sounds the same (except for a slight pitch shift).

Sorry if this disappoints you. I could add a disclaimer to the readme if you feel terribly wronged :-)

**Comment by ghost** [comment]
Well, can you develop a branch that does have infinite keys?

**Comment by fritzo** [comment]
Sorry, I have moved on to other things. Feel free to develop it yourself.
